// Plan state for the AI-driven import chat.
//
// One PlanState per chat session. The AI mutates it via tool calls; the UI
// re-renders from it. applyPlan.ts turns a PlanState into resolved rows per
// domain (drives both preview and commit). crossDomainCommit.ts inserts those
// rows in dependency order.
//
// sourceRows are parsed once at upload and never mutated again. Anything the
// AI wants to change (mapping, defaults, transforms, lookup choices) lives in
// per-target plans, which are pure data and replayable.

import { z } from "zod";

import type { ImportDomain } from "./schemas";

// ─── Transforms ────────────────────────────────────────────────────────────
//
// Each transform is a small declarative rule that applies to one resolved
// column on a target. Kept narrow on purpose: this is "clean up a messy
// spreadsheet", not ETL.

export const transformRuleSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("trim"), column: z.string() }),
  z.object({ kind: z.literal("uppercase"), column: z.string() }),
  z.object({ kind: z.literal("lowercase"), column: z.string() }),
  z.object({
    kind: z.literal("split_name"),
    sourceColumn: z.string(),
    firstInto: z.string(),
    lastInto: z.string(),
  }),
  z.object({
    kind: z.literal("regex_extract"),
    sourceColumn: z.string(),
    pattern: z.string(),
    intoColumn: z.string(),
  }),
  z.object({
    kind: z.literal("constant"),
    column: z.string(),
    value: z.union([z.string(), z.number(), z.boolean(), z.null()]),
  }),
]);
export type TransformRule = z.infer<typeof transformRuleSchema>;

// ─── Lookup resolution ─────────────────────────────────────────────────────
//
// One per (target, column, raw value). Tells applyPlan how to turn a raw
// string into a uuid, a sentinel for new-lookup creation, or null.

export const lookupResolutionSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("existing"), id: z.uuid() }),
  z.object({ kind: z.literal("create"), label: z.string().min(1) }),
  z.object({ kind: z.literal("skip") }),
]);
export type LookupResolution = z.infer<typeof lookupResolutionSchema>;

// ─── Row filter ────────────────────────────────────────────────────────────
// Optional. "Only import rows where column X matches one of these values."
// Kept as a single equality filter for now; can grow later if needed.

export const rowFilterSchema = z.object({
  sourceColumn: z.string(),
  matchAny: z.array(z.string()),
});
export type RowFilter = z.infer<typeof rowFilterSchema>;

// ─── Per-target plan ───────────────────────────────────────────────────────

export const targetPlanSchema = z.object({
  // excelHeader -> dbColumn. Missing entries mean "skip this excel column".
  mappings: z.record(z.string(), z.string()),
  // dbColumn -> default value used when no source column maps to it.
  defaults: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  transforms: z.array(transformRuleSchema),
  // `${dbColumn}::${rawValue}` -> resolution
  lookupChoices: z.record(z.string(), lookupResolutionSchema),
  rowFilter: rowFilterSchema.optional(),
});
export type TargetPlan = z.infer<typeof targetPlanSchema>;

export function emptyTargetPlan(): TargetPlan {
  return { mappings: {}, defaults: {}, transforms: [], lookupChoices: {} };
}

// ─── Cross-domain FK linking ───────────────────────────────────────────────
//
// "When you insert `from.fromColumn`, look it up against `to.toLabelColumn`
// from the rows we're inserting into `to.domain`, and use the new uuid."
// Example: passwords.client_id ← clients.name

export const fkLinkSchema = z.object({
  fromDomain: z.enum(["passwords", "clients", "suppliers"]),
  fromColumn: z.string(),   // the dbColumn on `fromDomain` rows to patch
  toDomain: z.enum(["passwords", "clients", "suppliers"]),
  toLabelColumn: z.string(), // dbColumn on `toDomain` rows whose value is the human key
});
export type FkLink = z.infer<typeof fkLinkSchema>;

// ─── Warnings ──────────────────────────────────────────────────────────────
//
// Per-cell or per-row notes the UI surfaces in the preview. Generated by both
// the AI (via note_warning tool) and applyPlan (when it had to make a call
// with no instructions).

export const planWarningSchema = z.object({
  domain: z.enum(["passwords", "clients", "suppliers"]),
  rowIndex: z.number().int().nullable(), // null = applies to all rows / target-wide
  column: z.string().nullable(),
  severity: z.enum(["info", "needs_input"]),
  message: z.string(),
  source: z.enum(["ai", "applyPlan"]),
});
export type PlanWarning = z.infer<typeof planWarningSchema>;

// ─── Chat transcript ───────────────────────────────────────────────────────

export const chatMessageSchema = z.object({
  role: z.enum(["user", "assistant"]),
  text: z.string(),
  // Tool calls the assistant made on this turn, recorded for audit. Free-form
  // since each tool has its own shape — validation happens when applied.
  toolCalls: z.array(z.object({ name: z.string(), args: z.unknown() })).default([]),
});
export type ChatMessage = z.infer<typeof chatMessageSchema>;

// ─── PlanState ────────────────────────────────────────────────────────────

export const sourceRowSchema = z.record(z.string(), z.unknown());
export type SourceRow = z.infer<typeof sourceRowSchema>;

export const planStateSchema = z.object({
  // Immutable after upload.
  sourceHeaders: z.array(z.string()),
  sourceRows: z.array(sourceRowSchema),
  // Which domain is the "home" of this import (the page the user is on).
  primaryDomain: z.enum(["passwords", "clients", "suppliers"]),
  // One entry per active target. Primary always present; cross-domain targets
  // appear only after the user accepts a propose_cross_domain_target turn.
  // Partial: only the primary domain is present until the user accepts a
  // cross-domain proposal. Zod 4's `record(enum, V)` is exhaustive (requires
  // every enum key) — `partialRecord` matches the `Partial<Record<...>>`
  // shape the rest of the code already assumes.
  targets: z.partialRecord(
    z.enum(["passwords", "clients", "suppliers"]),
    targetPlanSchema,
  ),
  links: z.array(fkLinkSchema),
  warnings: z.array(planWarningSchema),
  // Total Anthropic spend on this chat so far (for the cost cap).
  costUsdSpent: z.number().min(0),
  // Chat transcript so the AI sees prior turns and the audit log captures them.
  transcript: z.array(chatMessageSchema),
  // Bumped each successful turn so the server can spot stale client state.
  version: z.number().int().min(0),
});
export type PlanState = z.infer<typeof planStateSchema>;

// ─── Cost cap ─────────────────────────────────────────────────────────────
// Same cap as /admin/diagnostics — keeps a runaway chat bounded.
export const IMPORT_CHAT_COST_CAP_USD = 0.2;

// ─── Helpers ──────────────────────────────────────────────────────────────

export function initialPlanState(args: {
  primaryDomain: ImportDomain;
  sourceHeaders: string[];
  sourceRows: SourceRow[];
}): PlanState {
  return {
    sourceHeaders: args.sourceHeaders,
    sourceRows: args.sourceRows,
    primaryDomain: args.primaryDomain,
    targets: { [args.primaryDomain]: emptyTargetPlan() } as PlanState["targets"],
    links: [],
    warnings: [],
    costUsdSpent: 0,
    transcript: [],
    version: 0,
  };
}

export function activeDomains(state: PlanState): ImportDomain[] {
  return Object.keys(state.targets) as ImportDomain[];
}

export function lookupChoiceKey(dbColumn: string, rawValue: string): string {
  return `${dbColumn}::${rawValue}`;
}
